#+title: 12 Weeks Action Plan for my career change
#+date: [2025-12-27 Sat 18:36]
#+HUGO_BASE_DIR: /home/james/wiki/.site
#+HUGO_SECTION: 
#+HUGO_DRAFT: false
#+HUGO_DATE: 2025-12-27
#+EXPORT_FILE_NAME: 12-weeks-action-plan-for-my-career-change

* Context
:PROPERTIES:
:ID:       20251227T183632.488529
:END:

This plan is design with my current life circumstances in mind - working 20 hours and other things that are more private. I have also taken into consideration related skills and experiences that I already process.

I will also be documenting my progress as well as what I learn here.

* PHASE 1 - The Foundation and Certification
=WEEKS 1 - 4=

** Week 1: The Enterprise Linux Gap

This is where I will be bridge the knowledge gap between personal Linux and enterprise Linux.

+ [ ] Install a RHEL-based distro ( Set up Rocky Linux or Fedora in a VM ) 
+ [ ] Master Package Management ( =dnf= or =rpm= instead of =pacman= )
+ [ ] Learn SELinux ( Learn how to check logs and =audit2allow= )
+ [ ] Firewall ( Learn =firewalld= )
  
** Week 2: Networking Fundamentals 

+ [ ] CIDR Notation ( Subnet ranges )
+ [ ] DNS Debugging ( Master =dig= and =nslookup= )
+ [ ] HTTP Status Codes ( Memorise difference between 401/403 and 502/503 )
+ [ ] The Packet Journey ( Be able to explain what happens when you type an address into a browser, e.g. =growing.wiki= and =DNS= -> =IP= -> =TCP Handshake= -> =TLS= -> =HTTP= )
  
** Week 3 - 4:  AWS Certified Solutions Architect ( SAA-C03 )

+ [ ] Course ( Complete Adrian Cantrill's or Stephane Maarek's AWS SAA-C03 course. Skip "coding" parts and focus on =VPC=, =S3=, =EC2= and =IAM= )
+ [ ] Practice Exams ( TutorialsDojo practice exams )
+ [ ] Exam ( PASS IT )

* PHASE 2 - The "Literate DevOps" Portfolio
=WEEKS 5 - 8=

The goal here is to build two professional projects using org mode.

** Week 5: Tooling

+ [ ] Learn and set up LSP's ( =terraform-ls= and =docker-langserver= )
+ [ ] Set up Doom Emacs for writing code
  
** Week 6: Project A ( Static Site Migration =ongoingarchive.com= ) 

+ [ ] Architecture ( Migrate the site to =AWS S3= for storage and =CloudFront= for CDN )
+ [ ] Terraform ( Write a literate =org= file documenting both explanation and Terraform code, required resources: =aws_s3_bucket=, =aws_cloudfront_distribution=, =aws_route53_record= )
+ [ ] Security ( Implement Origin Access Control )
  
** Week 7: Project B ( Container Orchestration =growing.wiki= ) 

+ [ ] Containerise ( Write a multi-stage =Dockerfile=, from build stage to runtime stage, to keep the image small using Alpine Linux )
+ [ ] Orchestrate ( Use Terraform to deploy this to =AWS ECS Fargate= )
  + [ ] Create a =VPC= with Public/Private subnets
  + [ ] Put the Application Load Balancer ( =ALB= ) in Public
  + [ ] Put the Fargate Tasks ( Containers ) in Private
+ [ ] Outcome ( A URL that load balances traffic to the container )
  
** Week 8: CI/CD Automation

+ [ ] GitHub Actions ( Create a workflow for both projects )
  + [ ] Project A: =git push -> sync to S3 -> invalidate CloudFront cache=
  + [ ] Project B: =git push -> build Docker image -> push to AWS ECR -> force new ECS deployment=
  
* PHASE 3 - The Job Hunt
=WEEKS 9 - 12=

Basically at this point, what's left will be to get interviews and land a role using my resume and portfolio.

** Week 9: Resume Engineering 

+ [ ] Retail Translation ( Rewrite retail experience to  )
