#+title: 12 Weeks Action Plan for my career change
#+date: [2025-12-27 Sat 18:36]
#+HUGO_BASE_DIR: /home/james/wiki/.site
#+HUGO_SECTION: 
#+HUGO_DRAFT: false
#+HUGO_DATE: 2025-12-27
#+EXPORT_FILE_NAME: 12-weeks-action-plan-for-my-career-change

* Context
:PROPERTIES:
:ID:       20251227T183632.488529
:END:

This plan is design with my current life circumstances in mind - working 20 hours and other things that are more private. I have also taken into consideration related skills and experiences that I already process.

I will also be documenting my progress as well as what I learn here.

* PHASE 1 - The Foundation and Certification
=WEEKS 1 - 4=

** Week 1: The Enterprise Linux Gap

This is where I will be bridge the knowledge gap between personal Linux and enterprise Linux.

+ [ ] Install a RHEL-based distro ( Set up Rocky Linux or Fedora in a VM ) 
+ [ ] Master Package Management ( =dnf= or =rpm= instead of =pacman= )
+ [ ] Learn SELinux ( Learn how to check logs and =audit2allow= )
+ [ ] Firewall ( Learn =firewalld= )
  
** Week 2: Networking Fundamentals 

+ [ ] CIDR Notation ( Subnet ranges )
+ [ ] DNS Debugging ( Master =dig= and =nslookup= )
+ [ ] HTTP Status Codes ( Memorise difference between 401/403 and 502/503 )
+ [ ] The Packet Journey ( Be able to explain what happens when you type an address into a browser, e.g. =growing.wiki= and =DNS= -> =IP= -> =TCP Handshake= -> =TLS= -> =HTTP= )
  
** Week 3 - 4:  AWS Certified Solutions Architect ( SAA-C03 )

+ [ ] Course ( Complete Adrian Cantrill's or Stephane Maarek's AWS SAA-C03 course. Skip "coding" parts and focus on =VPC=, =S3=, =EC2= and =IAM= )
+ [ ] Practice Exams ( TutorialsDojo practice exams )

* PHASE 2

* PHASE 3  
