#+title: Hey there,
#+date: [2025-12-09 Tue]
#+HUGO_BASE_DIR: /home/james/wiki/.site
#+HUGO_SECTION: 
#+HUGO_DRAFT: false
#+HUGO_DATE: 2025-12-09
#+EXPORT_FILE_NAME: _index

* Welcome to Growing Wiki  🌱
:PROPERTIES:
:ID:       20251209T214330.737315
:END:

This is my personal notes wiki, using the [[id:20251212T222128.005838][working in public]] / [[id:20251212T222156.478599][digital garden]] method.
It is essentially an *always growing* collection of all my notes, ideas, thoughts and experiments that I want to share with the world, with you. 

#+BEGIN_QUOTE
It is *not* polished content; \\
It is *not* a blog; \\
It is a *work in progress* you can wander through and explore.
#+END_QUOTE

* How the website is built:

** Tools that I use

- Org mode for writing
- org-id for unbreakable links
- ox-hugo for export
- Hugo + Little Ocean theme for publishing

** My note taking workflow

1. Write notes in Org mode
2. Save automatically exports to Hugo via ox-hugo
3. Git commits and pushes automatically (enabled by default)
4. Website updates on Cloudflare Pages

Toggle auto-sync with =SPC n A= if you prefer manual control.

Start writing your first note!

* Linking

You can navigate with links like [[id:20251209T212256.718187][this]].

** Temporary (for testing purpose only)

[[id:20251212T151847.338743][Style Test]]
