#+title: 🪴 Welcome
#+date: [2025-12-09 Tue]
#+HUGO_BASE_DIR: /home/james/wiki/.site
#+HUGO_SECTION: 
#+HUGO_DRAFT: false
#+HUGO_DATE: 2025-12-09
#+EXPORT_FILE_NAME: _index

* 
:PROPERTIES:
:ID:       20251209T214330.737315
:END:

This is my personal notes wiki, using the [[id:20251212T222128.005838][learning in public]] / [[id:20251212T222156.478599][digital garden]] method.
This is an *always growing* collection of all my notes, ideas, thoughts and experiments that I want to share with the world, with you. 

#+BEGIN_VERSE
This is *NOT* polished content. \\
This is *NOT* a blog. \\
This is a *W-I-P* [fn:1] you can wander through and explore.
#+end_verse


** "Why?"

The original idea sprouted quite a while back. I would say ever since I have encountered Logseq, Obsidian and the idea of Zettelkasten.

I loved the idea of retaining knowledge through note taking and collection of information. 


* how the website is built:

** tools that i use

- org mode for writing
- org-id for unbreakable links
- ox-hugo for export
- hugo + little ocean theme for publishing

** my note taking workflow

1. write notes in org mode
2. save automatically exports to hugo via ox-hugo
3. git commits and pushes automatically (enabled by default)
4. website updates on cloudflare pages

toggle auto-sync with =spc n a= if you prefer manual control.

start writing your first note!

* linking

you can navigate with links like [[id:20251209T212256.718187][this]].

** temporary (for testing purpose only)

[[id:20251212T151847.338743][Style Test]]

------

[fn:1] Work-In-Progress or Work-In-Public
