#+title: Career Change - Week 0
#+date: [2025-12-28 Sun 13:19]
#+HUGO_BASE_DIR: /home/james/wiki/.site
#+HUGO_SECTION: 
#+HUGO_DRAFT: false
#+HUGO_DATE: 2025-12-28
#+EXPORT_FILE_NAME: career-change-week-0

* Nitro Boost ( for a head start )
:PROPERTIES:
:ID:       20251228T131932.226837
:END:

I gave myself a head start here, an initial "nitro boost" if you will.
So instead of starting on the 1st of January 2026 like any other "New Year's Resolution" project.
I dived right in, the very next day after making my [[id:20251227T183632.488529][12 weeks plan]] ( 2025-12-28 ).

* Virtual Machine 
[2025-12-28 Sun]

*Objective:*\\
Set up Virtual Machine and install a distro that's used for servers.

[[id:20251228T133642.919409][Here]] is how I do it for my purpose.

* Review
:LOGBOOK:
CLOCK: [2026-01-02 Fri 19:37]
:END:
[2026-01-02 Fri]

It turns out that I haven't manage to do much for Week 0, which is okay.
This project was not meant to be rushed, it would be better if I am able to
execute objectives properly rather than ticking off a list as fast as I can.

New year has already begun as the time of writing this. I have been quite anxious
about the future and my current state. I fear that I am not able to complete this project
in time, with the level of standard that I aim for. But worries stay as worries if no action
is taken. And I've already began taking actions. So the right thing to do right now is to
look forward and keep pushing for what I believe in.
