#+title: How to manage NPM packages on Arch Linux
#+date: [2025-12-27 Sat 21:08]
#+HUGO_BASE_DIR: /home/james/wiki/.site
#+HUGO_SECTION: 
#+HUGO_DRAFT: false
#+HUGO_DATE: 2025-12-27
#+EXPORT_FILE_NAME: how-to-manage-npm-packages-on-arch-linux

* What to avoid!
:PROPERTIES:
:ID:       20251227T210818.415689
:END:

Avoid using =sudo= with =npm= to install packages as this can lead to permission issues, security risks and conflicts with the =pacman= package manager.

* The "correct" methods
** Method 1 - Use a Version Manager

The first method is to use something like =fnm= ([[https://github.com/Schniz/fnm][Fast Node Manager]]) or =nvm= ([[https://github.com/nvm-sh/nvm][Node Version Manager]]).

These will allow you to install multiple versions of Node.js for development without the use of root privileges. Everything will be contained in your =$HOME= directory.

So if you're on Arch Linux, you can install the managers using =pacman= like:

#+begin_src bash
sudo pacman -S fnm
# or pacman -S nvm
#+end_src

You will then have to set up your shell, in my case =~/.zshrc=, like:

#+begin_src bash
eval "$(fnm evn --use-on-cd --shell zsh)"
#+end_src

And finally, install Node:

#+begin_src bash
fnm install --latest
#+end_src

** Method 2 - Change the default directory for =npm=

If you prefer to use the system Node package from you package manager, in my case, =sudo pacman -S nodejs npm=. You can redirect global installs (==npm install -g=) to your =$HOME= directory.

First, create a directory where global packages will be stored:

#+begin_src bash
mkdir -p ~/.local/share/npm-global # Or any directory names you fancy
#+end_src

Then configure =npm= to use this new path:

#+begin_src bash
npm config set prefix '~/.local/share/npm-global'
#+end_src

After that, you will then have to update your PATH. In my case, this would be =~/.zshrc=:

#+begin_src bash
export PATH="$HOME/.local/share/npm-global/bin:$PATH"
#+end_src

Before you test or use this method, you must first source the new configuration to refresh your shell:

#+begin_src bash
source ~/.zshrc
#+end_src
