#+title: Libvirt
#+date: [2026-01-02 Fri 20:01]
#+HUGO_BASE_DIR: /home/james/wiki/.site
#+HUGO_SECTION: 
#+HUGO_DRAFT: false
#+HUGO_DATE: 2026-01-02
#+EXPORT_FILE_NAME: libvirt

* TODO Content
:PROPERTIES:
:ID:       20260102T200157.820374
:END:

Libvirt is technically an open-source API, daemon (libvirtd), and management tool.

The main goal for Libvirt is to provide a single way to manage multiple different virtualisation
hypervisors. ( For example, [[id:20251228T134122.543389][KVM]]/[[id:20251228T190207.612738][QEMU]] in [[id:20251228T133642.919409][my use case]]. )

My understanding is that it provides a universal/unified way of operating and using a VM.
So it's basically serving as an abstraction layer to make doing things easier. For example,
instead of running long commands to execute actions like starting a VM, you simple rely on
Libvirt to "start" the VM regardless of the underlying technology.

* How does it relate to [[id:20251227T183632.488529][my plan]]?

The "Enterprise Perspective", if you will.

** Automation Compatibility

Modern tools like [[id:20260102T201231.900021][Terraform]], [[id:20260102T201238.961216][Ansible]] and [[id:20260102T201248.648900][Vagrant]] does not interact with [[id:20251228T190207.612738][QEMU]] or [[id:20251228T134122.543389][KVM]] directly.
This is where the Libvirt API comes in handy. Libvirt will be the interface that your
code will use.

** Virtualisation Unification

Libvirt doesn't only work for KVM, it is compatible with many other virtualisation tools.
This means that if I'm able to use =virsh= ( the CLI tool for Libvirt ), I will be
able to transfer the skill set across different enterprise environment.

** Security

For my use case ( learning VM using my local Arch machine ), Libvirt is managing most of the permissions for me. For instance, I would not require many elevated privileges or complex permissions required
by QEMU ( if running directly ). This ensures that my VM run with the minimum necessary access to my
host system ( Arch ), which in return makes it more "secure".



