#+title: Main Entrance
#+date: [2025-12-14 Sun 16:50]
#+HUGO_BASE_DIR: /home/james/wiki/.site
#+HUGO_SECTION: 
#+HUGO_DRAFT: false
#+HUGO_DATE: 2025-12-14
#+EXPORT_FILE_NAME: main-entrance

* What
:PROPERTIES:
:ID:       20251214T165008.884123
:END:

This is my attempt at growing my own [[id:20251214T182547.516206][Digital Garden]] and [[id:20251214T183616.136892][learning in public]].

In this ever-growing garden, you will find things like:
+ Rough ideas
+ Unfinished notes
+ Attempted writings
+ Brewing thoughts

The point is *not* to have a highly polished final piece to showcase;

Rather a W.I.P that is constantly evolving and *growing*, for the sake of always _learning_.

* Why

Because why not?

On a serious note, I find myself to be a very forgetful person. So to retain the content I consume, ideas that sparkled and notes that I plan on re-visiting; I have longed for a place to store, curate and recall everything.

I also find it super helpful to "grow" and "cultivate" my thoughts and ideas when trying to share it with a friend. It's very reminiscent of the [[id:20251215T151850.126685][rubber duck method]]. But instead of talking to a rubber duck, I choose to scream into the void of internet, to you.

As for why doing it this way, instead of x ... and more, find out [[id:20251215T151413.540793][here]].

* How 

This website is essentially my notebook that's kept in the open for everyone and anyone to see. I treat this as something like an [[https://obsidian.md/][Obsidian]] vault. The only difference being that it's public. I designed it to be this way to keep it as simple as possible, to reduce the friction to write and publish.

My workflow is something like:
=Write / Edit → Sync → Publish=

The underlined tools and programmes that I use are:
+ [[id:20251215T160403.586725][Emacs]] ( specifically [[https://github.com/doomemacs/doomemacs][Doom Emacs]] ) :: For editing =.org= files, which is the base file format.
+ [[https://ox-hugo.scripter.co/][Ox-Hugo]] :: For exporting =.org= files to =.md= files. 
+ [[https://gohugo.io/][Hugo]] :: Static site generator, or /"The world's fastest framework for building websites"/.
+ Git ( and currently [[https://github.com][GitHub]] ) ::  For version control and syncing remotely.
+ [[https:www.cloudflare.com][Cloudflare]] :: For domain management and hosting. 
