#+title: Main Entrance
#+date: [2025-12-14 Sun 16:50]
#+HUGO_BASE_DIR: /home/james/wiki/.site
#+HUGO_SECTION: 
#+HUGO_DRAFT: false
#+HUGO_DATE: 2025-12-14
#+EXPORT_FILE_NAME: main-entrance

* What
:PROPERTIES:
:ID:       20251214T165008.884123
:END:

This is my attempt at growing my own [[id:20251214T182547.516206][Digital Garden]] and [[id:20251214T183616.136892][learning in public]].

In this ever-growing garden, you will find things like:
+ Rough ideas
+ Unfinished notes
+ Attempted writings
+ Brewing thoughts

The point is *not* to have a highly polished final piece to showcase;

Rather a W.I.P that is constantly evolving and *growing*, for the sake of always _learning_.

* Why

Because why not?

On a serious note, I find myself to be a very forgetful person. So to retain the content I consume, ideas that sparkled and notes that I plan on re-visiting; I have longed for a place to store, curate and recall everything.

I also find it super helpful to "grow" and "cultivate" my thoughts and ideas when trying to share it with a friend. It's very reminiscent of the rubber duck method. But instead of talking to a rubber duck, I choose to scream into the void of internet, to you.

As for why doing it this way, instead of x ... and more, find out [[id:20251215T151413.540793][here]].

* How 

