#+title: Problem
#+date: [2025-12-08 Mon 16:56]
#+HUGO_BASE_DIR: /home/james/wiki/.site
#+HUGO_SECTION: 
#+HUGO_DRAFT: false
#+HUGO_DATE: 2025-12-08
#+EXPORT_FILE_NAME: Problem

* What this is
:PROPERTIES:
:ID:       20251209T175259.866567
:END:

This is my dotfiles for my Linux laptop using Emacs, org files and tangling, with Stow to symlink them.

The dotfiles.org was getting too large and harder to handle for AI agents.

So I have moved Doom config out of dotfiles.org into doom.org for easier indexing and searching. Can you make sure that it is able to tangle properly with the tangle.sh script like dotfiles.org is.

I will be dividing the dotfiles.org into smaller files later for better organisation and documentation. But hold that for now.

* Current project

I have used other AI agents to create functions and configs for using Emacs, org mode, ox-hugo and Hugo to automatically convert my .org note files into .md and then into a working website. The section is under heading "wiki" under "config.el".

** Problems needing attention
*** Links to heading are not recognised (ID links) - wiki/insert-heading-link
*** SPC n s (searching) is not working. No result shows. - wiki/search
*** Hugo related heading metadata isn't generated and added.
Hugo export code just seem to be quite bloated and buggy. Can you help me re-evaluate this bit and see what you can do.
** Re-evaluation
Re-evaluate the whole section if you need a better understanding of what it does. Also ask me about what I want to do if you are not sure. It's better to know what my needs than implementing features blindly.
