#+title: Setting up VM for enterprise environment
#+date: [2025-12-28 Sun 13:36]
#+HUGO_BASE_DIR: /home/james/wiki/.site
#+HUGO_SECTION: 
#+HUGO_DRAFT: false
#+HUGO_DATE: 2025-12-28
#+EXPORT_FILE_NAME: setting-up-vm-for-enterprise-environment

* The Enterprise Virtualization Stack 
:PROPERTIES:
:ID:       20251228T133642.919409
:END:

I will need to set up my instance of Virtual Machine in a way that sort of replicates a professional enterprise environment as closely as possible. 

So instead of using a third-party application like [[https://www.virtualbox.org/][VirtualBox]], I will instead go for the native Linux virtualisation stack.

** Components for the stack

+ [[id:20251228T134122.543389][KVM ( Kernel-based Virtual Machine )]] - Handles the heavy lifting of CPU and memory
+ [[id:20251228T190207.612738][QEMU]] - The "hands and feet" of the VM, providing the emulated hardware ( think USB ports and network cards, etc )
+ [[id:20260102T200157.820374][Libvirt]] - The "engine" or "nervous system" of the VM; The API that controls the brain and body.
+ [[id:20260102T202529.710382][Virt-manager]] - The "user interface" you interact with. [fn:: This is no longer part of the stack after [[id:20260102T205351.258562][consideration]]]
  
* Infrastructure Setup

I will be using =virt-install= to ensure the environment is reproducible.

** Preparation

Before that, we need to make sure that [[id:20260102T200157.820374][Libvirt]] is installed and =libvirtd= is running.

#+begin_src bash
sudo pacman -S libvirt

sudo systemctl enable libvirtd.service    # This will also enable virtlogd.socket
                                          # and virtlocked.socket

sudo systemctl start libvirtd.service
#+end_src

And we will also need a copy of the ISO, we could do so by using the =wget= to
download a copy from [[https://rockylinux.org/][Rocky Linux]]'s website. In this case, I chose the minimal
version which is likely to be better for learning purpose as we don't require
"unnecessary" tools that the default ships with.

#+begin_src bash
wget https://download.rockylinux.org/pub/rocky/10/isos/x86_64/Rocky-10.1-x86_64-minimal.iso ~/Download/
# This basically pulls the minimal version of ISO from their website
# and download it onto the "Download" folder in our home directory.
#+end_src

** Virsh

=Virsh= is the program we will use to manage our virtual machines in our terminal, without a GUI.
The command will be available as part of the =libvirt= library.

You can run an interactive terminal by simply running just =virsh=, which also has support for tab completion.

*** Storage *Pools*

To proceed with our installation of VM, we will need a specified location where our storage volume can be kept.
This is often called "virtual disks" or "virtual machine images" in other tools.

Pool locations can be:
+ directory
+ network filesystem
+ partition

Pools can also be *toggled* active or inactive and allocated for space.

**** Creating a new pool

There are couple of different ways to create a new pool, depending on the type
of pool you wish to use.

#+begin_src bash
virsh pool-define-as poolname /home/user/dir --targer /target/dir
#+end_src

Next up, we will have to build and start the pool that we've created:

#+begin_src bash
virsh pool-build poolname
virsh pool-start poolname
virsh pool-autostart poolname
#+end_src

** Domain

After the pool has been created and started successfully, we will need a domain.
This command does not only "install" but also defined the virtual hardware.

#+begin_src bash
virt-install \
    --name rocky-node-01 \
    --ram 2048 \
    --vcpus 2 \
    --os-variant rocky10 \
    --disk path=/var/lib/libvirt/images/rocky-node-01.qcow2,size=20,format=qcow2 \
    --location ~/Downloads/Rocky-10.1-x86_64-minimal.iso \
    --network network=default,model=virtio \
    --graphics none \
    --extra-args "console=ttyS0,115200n8"
#+end_src
