#+title: Virt-manager
#+date: [2026-01-02 Fri 20:25]
#+HUGO_BASE_DIR: /home/james/wiki/.site
#+HUGO_SECTION: 
#+HUGO_DRAFT: false
#+HUGO_DATE: 2026-01-02
#+EXPORT_FILE_NAME: virt-manager

* TODO What is Virt-manager?
:PROPERTIES:
:ID:       20260102T202529.710382
:END:

Virt-manager or Virtual Machine Manager, is essentially the GUI that the user will be interacting with to
manage the [[id:20260102T200157.820374][Libvirt]] API.

This means that you can use buttons, sliders and menus instead of writing XML code or long commands.

* Do we need this? ( For [[id:20251227T183632.488529][my plan]] )

** Advantage of using Virt-manager

Virt-manager is simply an UI for [[id:20260102T200157.820374][Libvirt]]; it generates the XML code and sends it to =libvirtd= without
it's own "logic".

A GUI will provide immediate visual feedback and this is very helpful for a beginner. You will be
more likely to spot any error that may occur as well as the reason or source of the error.

Virt-manager actually has an "XML" tab, where you are able to see the update to XML code upon changing a setting. This is a very useful way to learn the syntax without guessing.

** My worry

I worry that having a GUI will add an unnecessary "abstraction layer" to my learning process.
I would prefer to learn the XML code and CLI commands straightaway, which I believe is more
likely to be the case in a professional enterprise environment or work setting.

** Decision and shift

I think it is probably better for me to go down the "harder" route, replacing GUI "point and click" with:
+ Learning and using =virsh= commands.
+ Manually edit and define the XML code.
